services:
  stats:
    build: stats
    image: explore-with-me-stats
    container_name: explore-with-me-stats
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ewm_stats
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm

  ewm:
   build: main
   image: explore-with-me-main
   container_name: explore-with-me-main
   ports:
     - "8080:8080"
   depends_on:
     - db
   environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ewm_main
     - SPRING_DATASOURCE_USERNAME=ewm
     - SPRING_DATASOURCE_PASSWORD=ewm

  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_DB=ewm_stats
      - POSTGRES_DB=ewm_main
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10